#! /bin/bash
export DSLS_CONFIG=/var/DassaultSystemes/Licenses/DSLicSrv.txt
SEE_HOME=/app/DassaultSystemes/R2021x/3DOrchestrate
cd $SEE_HOME/linux_a64/reffiles/SMAExeServer/deploy

TEMP_CMD="$SEE_HOME/linux_a64/reffiles/SMAExeServer/deploy/smaexe-deploy.sh $SEE_HOME/config/deploy.param "

case "$1" in

'start')
     echo "Starting SEE Server..."
     $TEMP_CMD start
     $TEMP_CMD startstation
     ;;

'stop')

     echo "Stoping SEE Server..."
     $TEMP_CMD stopstation
     $TEMP_CMD stop
     ;;

'restart')
     echo "Starting SEE Server..."
     $TEMP_CMD stopstation
     $TEMP_CMD restart
     $TEMP_CMD startstation
     ;;

'restartstation')
     echo "Starting SEE Station..."
     $TEMP_CMD stopstation
     $TEMP_CMD startstation
     ;;

'status')
     echo "Starting SEE Server..."
     $TEMP_CMD status
     ;;

'-g')
     echo "Starting SEE Server..."
     $TEMP_CMD -g
     ;;

'')
     echo "Command Error. eg: ./smaexe start|stop|restart|status"
     ;;

esac

cd -


